# Generated by Django 4.1.13 on 2024-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytspotServer', '0005_playlistsqueries_playlist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsqueries',
            name='playlist_time',
            field=models.IntegerField(default=0),
        ),
    ]
